apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infras-cli
  namespace: infras-cli
  labels:
    app: infras-cli
  annotations:
    # Use NGINX ingress class
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: infras-cli.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infras-cli
                port:
                  number: 8000
