#!/usr/bin/env bash
set -euo pipefail

# This script initializes and unseals Vault, then writes secrets.
# It's designed to be run once.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
KEYS_FILE="${ROOT_DIR}/vault_keys.txt"

# Give Vault time to start
sleep 2

export VAULT_ADDR='http://127.0.0.1:8200'

# Define a helper function to run vault commands inside the container
# We will pass VAULT_TOKEN if it is set
run_vault() {
  if [ -n "${VAULT_TOKEN:-}" ]; then
    docker exec -e VAULT_TOKEN="$VAULT_TOKEN" vault-local vault "$@"
  else
    docker exec vault-local vault "$@"
  fi
}

# Function to generate a strong random password
# Length: 20, Alphanumeric (A-Z, a-z, 0-9)
generate_password() {
    # filtering for alphanumeric only, head -c 20
    # Use subshell to disable pipefail locally because head closes pipe causing SIGPIPE in tr
    (
        set +o pipefail
        LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 20
    )
}

# Check if Vault is already initialized
if run_vault status -format=json | jq -e '.initialized' > /dev/null; then
  echo "[INFO] Vault is already initialized. Unsealing..."
else
  echo "[INFO] Vault not initialized. Initializing..."
  # Initialize Vault and capture the output
  run_vault operator init -key-shares=1 -key-threshold=1 -format=json > "$KEYS_FILE"
  echo "[OK] Vault initialized. Unseal keys and root token saved to $KEYS_FILE"
fi

# Unseal Vault
UNSEAL_KEY=$(jq -r ".unseal_keys_b64[0]" "$KEYS_FILE")
run_vault operator unseal "$UNSEAL_KEY"
echo "[OK] Vault is unsealed."

# Log in with the root token
export VAULT_TOKEN=$(jq -r ".root_token" "$KEYS_FILE")
echo "[INFO] Logged in with root token."

# --- Write Secrets ---
echo "[INFO] Writing secrets to Vault..."

# Enable kv-v2 secrets engine at 'infras/' if not enabled
if ! run_vault secrets list -format=json | jq -e '."infras/"' > /dev/null; then
    echo "[INFO] Enabling kv-v2 secrets engine at infras/..."
    run_vault secrets enable -path=infras kv-v2
fi

# Enable kv-v2 secrets engine at 'apps/' if not enabled (initially empty but needed for app secrets)
if ! run_vault secrets list -format=json | jq -e '."apps/"' > /dev/null; then
    echo "[INFO] Enabling kv-v2 secrets engine at apps/..."
    run_vault secrets enable -path=apps kv-v2
fi

echo "[OK] Vault initialized and mounts enabled."

# --- Setup Userpass Auth ---
echo "[INFO] Configuring userpass auth for 'chown'..."
if ! run_vault auth list -format=json | jq -e '."userpass/"' > /dev/null; then
    run_vault auth enable userpass
fi

# Create a master admin policy for chown
cat <<EOF > /tmp/admin-policies.hcl
# Full admin policy - grants access to all operations

# Allow all operations on all paths
path "*" {
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

# System health checks
path "sys/health" {
  capabilities = ["read", "sudo"]
}

# Full access to all secrets engines
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
EOF
docker cp /tmp/admin-policies.hcl vault-local:/tmp/admin-policies.hcl
run_vault policy write admin-policies /tmp/admin-policies.hcl
rm -f /tmp/admin-policies.hcl

CHOWN_FILE="${ROOT_DIR}/vault_chown.txt"
if [ ! -f "$CHOWN_FILE" ]; then
    CHOWN_PASS=$(generate_password)
    run_vault write auth/userpass/users/chown password="$CHOWN_PASS" policies=admin-policies
    
    cat <<EOF > "$CHOWN_FILE"
USERNAME: chown
PASSWORD: $CHOWN_PASS
EOF
    echo "[OK] Created Vault 'chown' admin. Credentials saved to $CHOWN_FILE"
else
    echo "[INFO] Vault 'chown' user already configured ($CHOWN_FILE exists)."
fi

echo "[INFO] Admin secrets will be generated by respective service up.sh scripts."
echo "[OK] All secrets have been written to Vault."


