---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-vault
  labels:
    name: infras-vault
    project: k8s-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-kafka
  labels:
    name: infras-kafka
    project: k8s-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-mysql
  labels:
    name: infras-mysql
    project: k8s-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-postgres
  labels:
    name: infras-postgres
    project: k8s-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-redis
  labels:
    name: infras-redis
    project: k8s-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-keycloak
  labels:
    name: infras-keycloak
    project: k8s-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-monitoring
  labels:
    name: infras-monitoring
    project: k8s-local
---
apiVersion: v1
kind: Namespace
metadata:
  name: infras-management
  labels:
    name: infras-management
    project: k8s-local
