---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: infras-monitoring
data:
  grafana.ini: |
    [server]
    root_url = http://localhost:3000

    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db

    [session]
    provider = file

    [analytics]
    check_for_updates = false

    [log]
    mode = console
    level = info

    [users]
    default_theme = dark

    [auth.anonymous]
    enabled = true

  datasources.yaml: |
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true

  providers.yaml: |
    apiVersion: 1

    providers:
    - name: 'Dashboards'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
