apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: infras-vault
  labels:
    app: vault
    component: core

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault
  namespace: infras-vault
  labels:
    app: vault
    component: core
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault
  namespace: infras-vault
  labels:
    app: vault
    component: core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault
subjects:
- kind: ServiceAccount
  name: vault
  namespace: infras-vault
