#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
KEYS_FILE="${ROOT_DIR}/vault_keys.txt"
COMPOSE_FILE="${ROOT_DIR}/keycloak-local/docker-compose.yml"

# Source Common Library
source "${ROOT_DIR}/bin/lib/common.sh"

echo "[INFO] Starting keycloak-local..."

# Check Vault Availability
check_vault

if [ -n "${VAULT_TOKEN:-}" ]; then
    echo "[INFO] Vault detected. Ensuring/Fetching secrets..."
    
    # Ensure Keycloak Admin credential exists
    ensure_credential "infras/keycloak/auth" "admin"
    export KC_BOOTSTRAP_ADMIN_USERNAME=$(fetch_secret infras/keycloak/auth username)
    export KC_BOOTSTRAP_ADMIN_PASSWORD=$(fetch_secret infras/keycloak/auth password)
    
    # Check if DB is set up by checking if DB secret exists
    # fetch_secret might return empty if it doesn't exist
    db_pass=$(fetch_secret infras/postgres/keycloak password || true)
    if [ -n "$db_pass" ]; then
        echo "[INFO] DB secret found. Skipping DB setup."
    else
        echo "[INFO] DB secret not found. Running setup_acl.sh to create Keycloak DB and role..."
        "${ROOT_DIR}/bin/setup_acl.sh" keycloak postgres
    fi

    # Now fetch the DB credentials generated by setup_acl.sh
    export KEYCLOAK_DB_USERNAME=$(fetch_secret infras/postgres/keycloak username)
    export KEYCLOAK_DB_PASSWORD=$(fetch_secret infras/postgres/keycloak password)

    echo "[INFO] Secrets fetched successfully."
else
    echo "[WARN] Vault not detected. Ensure environment variables are set manually."
fi

echo "[INFO] Starting keycloak container..."
docker compose -f "${COMPOSE_FILE}" up -d

# Secondary Admin Setup
echo "[INFO] Waiting for Keycloak to be healthy before configuring secondary admin 'chown'..."
while ! curl -s http://localhost:18080/health/ready > /dev/null; do
    sleep 5
done

echo "[INFO] Keycloak is ready. Checking/Configuring secondary 'chown' admin account..."
ensure_credential "infras/keycloak/users/chown" "chown"
chown_pass=$(fetch_secret infras/keycloak/users/chown password)

# Re-fetch bootstrap admin credentials
admin_user=$(fetch_secret infras/keycloak/auth username)
admin_pass=$(fetch_secret infras/keycloak/auth password)

# Forcefully bootstrap admin user in case environment variables were ignored by Keycloak
docker exec -e KEYCLOAK_TMP_PASS="$admin_pass" keycloak-local /opt/keycloak/bin/kc.sh bootstrap-admin user --username "$admin_user" --password:env KEYCLOAK_TMP_PASS >/dev/null 2>&1 || true

# Authenticate with Keycloak Admin CLI
docker exec keycloak-local /opt/keycloak/bin/kcadm.sh config credentials \
    --server http://localhost:8080 --realm master --user "$admin_user" --password "$admin_pass" >/dev/null

# Check if chown exists and create if not
chown_exists=$(docker exec keycloak-local /opt/keycloak/bin/kcadm.sh get users -r master -q username=chown | jq -r '.[0] // empty' || true)

if [ -z "$chown_exists" ] || [ "$chown_exists" = "null" ]; then
    echo "[INFO] Creating secondary admin 'chown' in master realm..."
    docker exec keycloak-local /opt/keycloak/bin/kcadm.sh create users -r master -s username=chown -s enabled=true >/dev/null
    
    # Assign global 'admin' role
    docker exec keycloak-local /opt/keycloak/bin/kcadm.sh add-roles -r master --uusername chown --rolename admin >/dev/null
else
    echo "[INFO] Secondary admin 'chown' already exists. Updating password to ensure match..."
fi

# Enforce user password idempotently
docker exec keycloak-local /opt/keycloak/bin/kcadm.sh set-password -r master --username chown --new-password "$chown_pass" >/dev/null
echo "[OK] Secondary admin 'chown' is ready and its password is in Vault!"
