version: "3.8"

services:
  kafka-1:
    image: confluentinc/cp-kafka:7.6.1
    platform: linux/amd64
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "9092:19092" # External PLAINTEXT
      - "9095:19095" # External SASL
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      
      # --- Listeners ---
      KAFKA_LISTENERS: 'BROKER://:9091,CONTROLLER://:9093,EXTERNAL://:19092,INTERNAL_CLIENT://:19095,DOCKER_CLIENT://:29095'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka-1:9091,EXTERNAL://localhost:9092,INTERNAL_CLIENT://localhost:9095,DOCKER_CLIENT://kafka-1:29095'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'BROKER'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL_CLIENT:SASL_PLAINTEXT,DOCKER_CLIENT:SASL_PLAINTEXT'

      # --- SASL Auth ---
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      # Inter-broker client credentials (so this broker authenticates to peers as kafka-1)
      KAFKA_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-1" password="${KAFKA_1_PASSWORD}";'
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-1" password="${KAFKA_1_PASSWORD}";'

      # --- KRaft Settings ---
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:kafka-1;User:kafka-2;User:kafka-3
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    command:
      - bash
      - -c
      - |
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo "Formatting storage..."
          kafka-storage format -t $CLUSTER_ID -c /etc/kafka/server.properties
        fi
        /etc/confluent/docker/run
    volumes:
      - ../volumes/kafka-1-data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  kafka-2:
    image: confluentinc/cp-kafka:7.6.1
    platform: linux/amd64
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "9093:19093" # External PLAINTEXT
      - "9096:19096" # External SASL
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LISTENERS: 'BROKER://:9091,CONTROLLER://:9093,EXTERNAL://:19093,INTERNAL_CLIENT://:19096,DOCKER_CLIENT://:29096'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka-2:9091,EXTERNAL://localhost:9093,INTERNAL_CLIENT://localhost:9096,DOCKER_CLIENT://kafka-2:29096'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'BROKER'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL_CLIENT:SASL_PLAINTEXT,DOCKER_CLIENT:SASL_PLAINTEXT'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      # Inter-broker client credentials (so this broker authenticates to peers as kafka-2)
      KAFKA_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-2" password="${KAFKA_2_PASSWORD}";'
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-2" password="${KAFKA_2_PASSWORD}";'
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:kafka-1;User:kafka-2;User:kafka-3
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    command:
      - bash
      - -c
      - |
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo "Formatting storage..."
          kafka-storage format -t $CLUSTER_ID -c /etc/kafka/server.properties
        fi
        /etc/confluent/docker/run
    volumes:
      - ../volumes/kafka-2-data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  kafka-3:
    image: confluentinc/cp-kafka:7.6.1
    platform: linux/amd64
    container_name: kafka-3
    hostname: kafka-3
    ports:
      - "9094:19094" # External PLAINTEXT
      - "9097:19097" # External SASL
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LISTENERS: 'BROKER://:9091,CONTROLLER://:9093,EXTERNAL://:19094,INTERNAL_CLIENT://:19097,DOCKER_CLIENT://:29097'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka-3:9091,EXTERNAL://localhost:9094,INTERNAL_CLIENT://localhost:9097,DOCKER_CLIENT://kafka-3:29097'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'BROKER'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL_CLIENT:SASL_PLAINTEXT,DOCKER_CLIENT:SASL_PLAINTEXT'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      # Inter-broker client credentials (so this broker authenticates to peers as kafka-3)
      KAFKA_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-3" password="${KAFKA_3_PASSWORD}";'
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-3" password="${KAFKA_3_PASSWORD}";'
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:kafka-1;User:kafka-2;User:kafka-3
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    command:
      - bash
      - -c
      - |
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo "Formatting storage..."
          kafka-storage format -t $CLUSTER_ID -c /etc/kafka/server.properties
        fi
        /etc/confluent/docker/run
    volumes:
      - ../volumes/kafka-3-data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

volumes:
  kafka-1-data:
    name: kafka-1-data
  kafka-2-data:
    name: kafka-2-data
  kafka-3-data:
    name: kafka-3-data
